# Compose runtime environment variables
x-client-variables: &client-variables
  PORT: ${PORT:-3000}

# Extended Services Definition
services:
  client:
    image: ${COMPOSE_PROJECT_NAME}_client:local
    build:
      dockerfile: docker/Dockerfile-client.local
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      <<: *client-variables
