steps:
  #################################################################
  # Build
  #################################################################
  - name: "docker/compose:1.29.2"
    args: [
      "build",
      "client"
    ]
    env:
      - "COMPOSE_FILE=docker/docker-compose.yml:docker/docker-compose.cd.yml"
      - "COMPOSE_PROJECT_NAME=frontend-booster-nextjs"

  #################################################################
  # Tag
  #################################################################
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "frontend-booster-nextjs_client:cd",
      "gcr.io/$PROJECT_ID/client:$SHORT_SHA"
    ]

  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "frontend-booster-nextjs_client:cd",
      "gcr.io/$PROJECT_ID/client:development"
    ]

  #################################################################
  # Push
  #################################################################
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/$PROJECT_ID/client"
    ]

  #################################################################
  # Deploy
  #################################################################
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: [
      "run",
      "deploy",
      "client-development",
      "--allow-unauthenticated",
      "--platform", "managed",
      "--region", "us-central1",
      "--image", "gcr.io/$PROJECT_ID/client:development"
    ]
